# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pay.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(733, 501)
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(320, 410, 111, 41))
        self.back.setObjectName("back")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(210, 90, 311, 251))
        self.label.setObjectName("label")
        self.total = QtWidgets.QLineEdit(Form)
        self.total.setGeometry(QtCore.QRect(230, 20, 281, 41))
        self.total.setObjectName("total")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "My Form"))
        self.back.setText(_translate("Form", "返回"))
        self.label.setText(_translate("Form", "picture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
